//图书优惠规则
package book.discount
import com.czc.example.flink.drools.entity.BuizOrder

//规则一：所购图书总价在100元以下的没有优惠
rule "book_discount_1"
    when
        $order:BuizOrder(originalPrice < 100)
    then
        $order.realPrice_$eq($order.originalPrice());
        System.out.println("成功匹配到规则一：所购图书总价在100元以下的没有优惠");
end

//规则二：所购图书总价在100到200元的优惠20元
rule "book_discount_2"
    when
        $order:BuizOrder(originalPrice < 200 && originalPrice >= 100)
    then
        $order.realPrice_$eq($order.originalPrice() - 20);
        System.out.println("成功匹配到规则二：所购图书总价在100到200元的优惠20元");
end

//规则三：所购图书总价在200到300元的优惠50元
rule "book_discount_3"
    when
        $order:BuizOrder(originalPrice <= 300 && originalPrice >= 200)
    then
        $order.realPrice_$eq($order.originalPrice() - 50);
        System.out.println("成功匹配到规则三：所购图书总价在200到300元的优惠50元");
end

//规则四：所购图书总价在300元以上的优惠100元
rule "book_discount_4"
    when
        $order:BuizOrder(originalPrice >= 300)
    then
        $order.realPrice_$eq($order.originalPrice() - 100);
        System.out.println("成功匹配到规则四：所购图书总价在300元以上的优惠100元");
end